apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: todo-app
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=          # echo -n "postgres" | base64
  DB_PASSWORD: cGFzc3dvcmQ=      # echo -n "password" | base64