apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: todo-app
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: postgres:13
        command: ["psql", "-h", "postgres-service", "-U", "postgres", "-d", "todos", "-c", "CREATE TABLE IF NOT EXISTS todos (id SERIAL PRIMARY KEY, text VARCHAR(255) NOT NULL, completed BOOLEAN DEFAULT FALSE);"]
        env:
        - name: PGPASSWORD
          value: "password"
      restartPolicy: Never
  backoffLimit: 3